# Generated by Django 4.1.5 on 2023-01-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments_api", "0004_alter_paymentdebt_government_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCredit",
            fields=[
                ("credit_id", models.AutoField(primary_key=True, serialize=False)),
                ("paid_at", models.DateTimeField()),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_by", models.CharField(max_length=100)),
                (
                    "debt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_credit",
                        to="payments_api.paymentdebt",
                    ),
                ),
            ],
        ),
    ]
